/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE8 (number 11), LED1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED1_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED1_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE9 (number 12), LED2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED2_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTD8 (number 137), DSPdp
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPdp_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPdp_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPdp_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPdp_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPdp_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD9 (number 138), DSPa
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPa_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPa_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPa_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPa_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPa_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTD10 (number 139), DSPb
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPb_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPb_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPb_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPb_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPb_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD11 (number 140), DSPc
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPc_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPc_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPc_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPc_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPc_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD12 (number 141), DSPd
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPd_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPd_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPd_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPd_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPd_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD13 (number 142), DSPe
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPe_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPe_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPe_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPe_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPe_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD14 (number 143), DSPf
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPf_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPf_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPf_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPf_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPf_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD15 (number 144), DSPg
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSPg_GPIO GPIOD                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DSPg_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DSPg_PORT PORTD                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DSPg_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DSPg_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTE12 (number 15), BEEP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BEEP_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BEEP_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BEEP_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BEEP_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BEEP_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB17 (number 96), KEY1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY1_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY1_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY1_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY1_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB18 (number 97), KEY2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY2_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC7 (number 112), SW1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW1_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW1_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC16 (number 123), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW2_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW2_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW2_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC17 (number 124), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW3_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW3_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW3_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW3_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW3_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC18 (number 125), SW4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW4_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW4_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW4_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW4_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW4_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB20 (number 99), QESa
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_QESa_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_QESa_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_QESa_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_QESa_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_QESa_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB19 (number 98), QESb
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_QESb_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_QESb_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_QESb_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_QESb_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_QESb_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB21 (number 100), QESp
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_QESp_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_QESp_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_QESp_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_QESp_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_QESp_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTE11 (number 14), I2C3_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_SCL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_SCL_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_SCL_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE10 (number 13), I2C3_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_SDA_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_SDA_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_SDA_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA26 (number 77), OLED_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_SCL_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_SCL_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_SCL_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_SCL_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_SCL_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA27 (number 78), OLED_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_SDA_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_SDA_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_SDA_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_SDA_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_SDA_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA28 (number 79), OLED_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_RST_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_RST_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_RST_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_RST_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_RST_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA29 (number 80), OLED_DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_OLED_DC_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_OLED_DC_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_DC_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_DC_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_DC_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
